import type { ComponentType, Styles } from '@/types/canvas';

export type BlueprintCategory =
  | 'basic'
  | 'layout'
  | 'media'
  | 'form'
  | 'navigation'
  | 'data'
  | 'feedback'
  | 'typography'
  | 'templates';

export interface ComponentBlueprint {
  type: ComponentType;
  label: string;
  description: string;
  icon: string;
  category: BlueprintCategory;
  defaultStyles: Partial<Styles>;
  defaultProps: Record<string, unknown>;
}

export const componentBlueprints: ComponentBlueprint[] = [
  // ===== BASIC =====
  {
    type: 'box',
    label: 'Box',
    description: 'A generic container for grouping elements',
    icon: '□',
    category: 'basic',
    defaultStyles: {
      display: { base: 'block' },
      padding: { base: '16px' },
      backgroundColor: { base: '#f3f4f6' },
      borderRadius: { base: '8px' },
    },
    defaultProps: {},
  },
  {
    type: 'text',
    label: 'Text',
    description: 'Add a text paragraph or heading',
    icon: 'T',
    category: 'basic',
    defaultStyles: {
      display: { base: 'block' },
      fontSize: { base: '16px' },
      color: { base: '#374151' },
    },
    defaultProps: { text: 'New Text' },
  },
  {
    type: 'button',
    label: 'Button',
    description: 'Interactive clickable button',
    icon: '●',
    category: 'basic',
    defaultStyles: {
      display: { base: 'inline-block' },
      padding: { base: '8px 16px' },
      backgroundColor: { base: '#8b5cf6' },
      color: { base: '#ffffff' },
      borderRadius: { base: '6px' },
      fontWeight: { base: '500' },
      cursor: { base: 'pointer' },
    },
    defaultProps: { text: 'Button', type: 'button' },
  },
  {
    type: 'badge',
    label: 'Badge',
    description: 'Small label for status or counts',
    icon: '◆',
    category: 'basic',
    defaultStyles: {
      display: { base: 'inline-block' },
      padding: { base: '2px 8px' },
      backgroundColor: { base: '#8b5cf6' },
      color: { base: '#ffffff' },
      borderRadius: { base: '999px' },
      fontSize: { base: '12px' },
      fontWeight: { base: '600' },
    },
    defaultProps: { text: 'Badge' },
  },
  {
    type: 'chip',
    label: 'Chip / Tag',
    description: 'Filterable tag or label',
    icon: '🏷',
    category: 'basic',
    defaultStyles: {
      display: { base: 'inline-flex' },
      padding: { base: '4px 10px' },
      backgroundColor: { base: '#e5e7eb' },
      color: { base: '#374151' },
      borderRadius: { base: '6px' },
      fontSize: { base: '13px' },
      fontWeight: { base: '500' },
      alignItems: { base: 'center' },
      gap: { base: '4px' },
    },
    defaultProps: { text: 'Tag' },
  },
  {
    type: 'tooltip',
    label: 'Tooltip',
    description: 'Hover tooltip wrapper',
    icon: '💬',
    category: 'basic',
    defaultStyles: {
      display: { base: 'inline-block' },
      position: { base: 'relative' },
      cursor: { base: 'pointer' },
    },
    defaultProps: { text: 'Hover me', label: 'Tooltip content' },
  },
  {
    type: 'divider',
    label: 'Divider',
    description: 'Horizontal separating line',
    icon: '—',
    category: 'basic',
    defaultStyles: {
      width: { base: '100%' },
      height: { base: '1px' },
      backgroundColor: { base: '#d1d5db' },
      margin: { base: '16px 0' },
    },
    defaultProps: {},
  },

  // ===== FORM =====
  {
    type: 'input',
    label: 'Input',
    description: 'Text input field',
    icon: '▤',
    category: 'form',
    defaultStyles: {
      display: { base: 'block' },
      width: { base: '100%' },
      padding: { base: '8px 12px' },
      borderWidth: { base: '1px' },
      borderStyle: { base: 'solid' },
      borderColor: { base: '#d1d5db' },
      borderRadius: { base: '6px' },
      fontSize: { base: '14px' },
      backgroundColor: { base: '#ffffff' },
      color: { base: '#111827' },
    },
    defaultProps: { placeholder: 'Enter text...', type: 'text' },
  },
  {
    type: 'textarea',
    label: 'Textarea',
    description: 'Multi-line text input',
    icon: '▨',
    category: 'form',
    defaultStyles: {
      display: { base: 'block' },
      width: { base: '100%' },
      minHeight: { base: '80px' },
      padding: { base: '8px 12px' },
      borderWidth: { base: '1px' },
      borderStyle: { base: 'solid' },
      borderColor: { base: '#d1d5db' },
      borderRadius: { base: '6px' },
      fontSize: { base: '14px' },
      backgroundColor: { base: '#ffffff' },
      color: { base: '#111827' },
    },
    defaultProps: { placeholder: 'Enter text...', rows: 4 },
  },
  {
    type: 'select',
    label: 'Select',
    description: 'Dropdown select field',
    icon: '▼',
    category: 'form',
    defaultStyles: {
      display: { base: 'block' },
      width: { base: '100%' },
      padding: { base: '8px 12px' },
      borderWidth: { base: '1px' },
      borderStyle: { base: 'solid' },
      borderColor: { base: '#d1d5db' },
      borderRadius: { base: '6px' },
      fontSize: { base: '14px' },
      backgroundColor: { base: '#ffffff' },
      color: { base: '#111827' },
    },
    defaultProps: { options: 'Option 1\nOption 2\nOption 3' },
  },
  {
    type: 'checkbox',
    label: 'Checkbox',
    description: 'Checkbox input with label',
    icon: '☑',
    category: 'form',
    defaultStyles: {
      display: { base: 'inline-flex' },
      alignItems: { base: 'center' },
      gap: { base: '8px' },
      cursor: { base: 'pointer' },
      fontSize: { base: '14px' },
    },
    defaultProps: { label: 'Checkbox', checked: false },
  },
  {
    type: 'radio',
    label: 'Radio',
    description: 'Radio input with label',
    icon: '◉',
    category: 'form',
    defaultStyles: {
      display: { base: 'inline-flex' },
      alignItems: { base: 'center' },
      gap: { base: '8px' },
      cursor: { base: 'pointer' },
      fontSize: { base: '14px' },
    },
    defaultProps: { label: 'Option', checked: false },
  },
  {
    type: 'switch',
    label: 'Switch',
    description: 'Toggle switch control',
    icon: '⤶',
    category: 'form',
    defaultStyles: {
      display: { base: 'inline-flex' },
      alignItems: { base: 'center' },
      gap: { base: '8px' },
      cursor: { base: 'pointer' },
    },
    defaultProps: { label: 'Toggle', checked: false },
  },

  // ===== NAVIGATION =====
  {
    type: 'navbar',
    label: 'Navbar',
    description: 'Top navigation bar with links',
    icon: '☰',
    category: 'navigation',
    defaultStyles: {
      display: { base: 'flex' },
      width: { base: '100%' },
      padding: { base: '12px 24px' },
      backgroundColor: { base: '#ffffff' },
      borderBottom: { base: '1px solid #e5e7eb' },
      alignItems: { base: 'center' },
      justifyContent: { base: 'space-between' },
    },
    defaultProps: { items: 'Home\nAbout\nContact' },
  },
  {
    type: 'tabs',
    label: 'Tabs',
    description: 'Tabbed content switcher',
    icon: '▦',
    category: 'navigation',
    defaultStyles: {
      display: { base: 'flex' },
      width: { base: '100%' },
      gap: { base: '0' },
      borderBottom: { base: '2px solid #e5e7eb' },
    },
    defaultProps: { items: 'Tab 1\nTab 2\nTab 3' },
  },
  {
    type: 'accordion',
    label: 'Accordion',
    description: 'Collapsible content panel',
    icon: '≡',
    category: 'navigation',
    defaultStyles: {
      display: { base: 'block' },
      width: { base: '100%' },
      borderWidth: { base: '1px' },
      borderStyle: { base: 'solid' },
      borderColor: { base: '#e5e7eb' },
      borderRadius: { base: '8px' },
      overflow: { base: 'hidden' },
    },
    defaultProps: { text: 'Accordion Item' },
  },
  {
    type: 'dropdown',
    label: 'Dropdown',
    description: 'Dropdown menu button',
    icon: '↕',
    category: 'navigation',
    defaultStyles: {
      display: { base: 'inline-block' },
      position: { base: 'relative' },
    },
    defaultProps: { text: 'Dropdown', items: 'Item 1\nItem 2\nItem 3' },
  },
  {
    type: 'breadcrumbs',
    label: 'Breadcrumbs',
    description: 'Navigation breadcrumb path',
    icon: '›',
    category: 'navigation',
    defaultStyles: {
      display: { base: 'flex' },
      alignItems: { base: 'center' },
      gap: { base: '8px' },
      fontSize: { base: '14px' },
      color: { base: '#6b7280' },
    },
    defaultProps: { items: 'Home / Page / Subpage' },
  },

  // ===== DATA =====
  {
    type: 'table',
    label: 'Table',
    description: 'Data table with rows and columns',
    icon: '⊞',
    category: 'data',
    defaultStyles: {
      display: { base: 'table' },
      width: { base: '100%' },
      borderCollapse: { base: 'collapse' },
      fontSize: { base: '14px' },
    },
    defaultProps: {
      columns: 'Name,Email,Role',
      items: 'John,john@acme.com,Admin\nJane,jane@acme.com,Editor\nBob,bob@acme.com,Viewer',
    },
  },
  {
    type: 'card',
    label: 'Card',
    description: 'Content card with shadow',
    icon: '▨',
    category: 'data',
    defaultStyles: {
      display: { base: 'block' },
      padding: { base: '24px' },
      backgroundColor: { base: '#ffffff' },
      borderRadius: { base: '12px' },
      boxShadow: { base: '0 1px 3px rgba(0,0,0,0.1), 0 1px 2px rgba(0,0,0,0.06)' },
    },
    defaultProps: {},
  },
  {
    type: 'avatar',
    label: 'Avatar',
    description: 'User profile image',
    icon: '◎',
    category: 'data',
    defaultStyles: {
      display: { base: 'inline-block' },
      width: { base: '40px' },
      height: { base: '40px' },
      borderRadius: { base: '999px' },
      objectFit: { base: 'cover' },
    },
    defaultProps: { src: '', alt: 'Avatar' },
  },

  // ===== FEEDBACK =====
  {
    type: 'alert',
    label: 'Alert',
    description: 'Notification alert box',
    icon: '⚠',
    category: 'feedback',
    defaultStyles: {
      display: { base: 'flex' },
      width: { base: '100%' },
      padding: { base: '12px 16px' },
      backgroundColor: { base: '#fef3cd' },
      borderWidth: { base: '1px' },
      borderStyle: { base: 'solid' },
      borderColor: { base: '#ffc107' },
      borderRadius: { base: '8px' },
      color: { base: '#856404' },
      fontSize: { base: '14px' },
      alignItems: { base: 'center' },
      gap: { base: '8px' },
    },
    defaultProps: { text: 'This is an alert message' },
  },
  {
    type: 'toast',
    label: 'Toast',
    description: 'Floating notification',
    icon: '🔔',
    category: 'feedback',
    defaultStyles: {
      display: { base: 'flex' },
      padding: { base: '12px 16px' },
      backgroundColor: { base: '#1f2937' },
      color: { base: '#ffffff' },
      borderRadius: { base: '8px' },
      fontSize: { base: '14px' },
      alignItems: { base: 'center' },
      gap: { base: '8px' },
      boxShadow: { base: '0 10px 15px -3px rgba(0,0,0,0.1)' },
    },
    defaultProps: { text: 'Toast notification' },
  },
  {
    type: 'modal',
    label: 'Modal',
    description: 'Dialog overlay panel',
    icon: '▣',
    category: 'feedback',
    defaultStyles: {
      display: { base: 'block' },
      padding: { base: '24px' },
      backgroundColor: { base: '#ffffff' },
      borderRadius: { base: '12px' },
      boxShadow: { base: '0 25px 50px -12px rgba(0,0,0,0.25)' },
      maxWidth: { base: '500px' },
      width: { base: '100%' },
    },
    defaultProps: { text: 'Modal Content' },
  },
  {
    type: 'progress',
    label: 'Progress Bar',
    description: 'Progress indicator bar',
    icon: '▤',
    category: 'feedback',
    defaultStyles: {
      display: { base: 'block' },
      width: { base: '100%' },
      height: { base: '8px' },
      backgroundColor: { base: '#e5e7eb' },
      borderRadius: { base: '999px' },
      overflow: { base: 'hidden' },
    },
    defaultProps: { value: '60' },
  },
  {
    type: 'skeleton',
    label: 'Skeleton',
    description: 'Loading placeholder',
    icon: '▭',
    category: 'feedback',
    defaultStyles: {
      display: { base: 'block' },
      width: { base: '100%' },
      height: { base: '20px' },
      backgroundColor: { base: '#e5e7eb' },
      borderRadius: { base: '4px' },
    },
    defaultProps: {},
  },

  // ===== LAYOUT =====
  {
    type: 'container',
    label: 'Container',
    description: 'Full-width content container',
    icon: '▢',
    category: 'layout',
    defaultStyles: {
      display: { base: 'block' },
      width: { base: '100%' },
      padding: { base: '16px' },
      minHeight: { base: '60px' },
      backgroundColor: { base: '#f9fafb' },
      borderRadius: { base: '8px' },
      borderWidth: { base: '1px' },
      borderStyle: { base: 'dashed' },
      borderColor: { base: '#d1d5db' },
    },
    defaultProps: {},
  },
  {
    type: 'flex',
    label: 'Flex Container',
    description: 'Flexible box layout container',
    icon: '≡',
    category: 'layout',
    defaultStyles: {
      display: { base: 'flex' },
      flexDirection: { base: 'row' },
      gap: { base: '8px' },
      padding: { base: '16px' },
      minHeight: { base: '80px' },
      backgroundColor: { base: '#f9fafb' },
      borderRadius: { base: '8px' },
      borderWidth: { base: '1px' },
      borderStyle: { base: 'dashed' },
      borderColor: { base: '#d1d5db' },
    },
    defaultProps: {},
  },
  {
    type: 'grid',
    label: 'Grid Container',
    description: 'CSS Grid layout container',
    icon: '⊞',
    category: 'layout',
    defaultStyles: {
      display: { base: 'grid' },
      gridTemplateColumns: { base: '1fr 1fr' },
      gap: { base: '8px' },
      padding: { base: '16px' },
      minHeight: { base: '120px' },
      backgroundColor: { base: '#f9fafb' },
      borderRadius: { base: '8px' },
      borderWidth: { base: '1px' },
      borderStyle: { base: 'dashed' },
      borderColor: { base: '#d1d5db' },
    },
    defaultProps: {},
  },
  {
    type: 'sidebar',
    label: 'Sidebar',
    description: 'Side navigation panel',
    icon: '▌',
    category: 'layout',
    defaultStyles: {
      display: { base: 'block' },
      width: { base: '280px' },
      minHeight: { base: '400px' },
      padding: { base: '16px' },
      backgroundColor: { base: '#f9fafb' },
      borderRight: { base: '1px solid #e5e7eb' },
    },
    defaultProps: {},
  },
  {
    type: 'header',
    label: 'Header',
    description: 'Page header section',
    icon: '▔',
    category: 'layout',
    defaultStyles: {
      display: { base: 'block' },
      width: { base: '100%' },
      padding: { base: '16px 24px' },
      backgroundColor: { base: '#ffffff' },
      borderBottom: { base: '1px solid #e5e7eb' },
    },
    defaultProps: { text: 'Header' },
  },
  {
    type: 'footer',
    label: 'Footer',
    description: 'Page footer section',
    icon: '▁',
    category: 'layout',
    defaultStyles: {
      display: { base: 'block' },
      width: { base: '100%' },
      padding: { base: '24px' },
      backgroundColor: { base: '#1f2937' },
      color: { base: '#f9fafb' },
      fontSize: { base: '14px' },
    },
    defaultProps: { text: 'Footer content' },
  },
  {
    type: 'section',
    label: 'Section',
    description: 'Content section wrapper',
    icon: '▬',
    category: 'layout',
    defaultStyles: {
      display: { base: 'block' },
      width: { base: '100%' },
      padding: { base: '48px 24px' },
    },
    defaultProps: {},
  },
  {
    type: 'hero',
    label: 'Hero Section',
    description: 'Large hero banner with heading',
    icon: '★',
    category: 'layout',
    defaultStyles: {
      display: { base: 'flex' },
      flexDirection: { base: 'column' },
      width: { base: '100%' },
      minHeight: { base: '400px' },
      padding: { base: '64px 24px' },
      backgroundColor: { base: '#f3f4f6' },
      alignItems: { base: 'center' },
      justifyContent: { base: 'center' },
      gap: { base: '16px' },
      textAlign: { base: 'center' },
    },
    defaultProps: { text: 'Hero Title' },
  },
  {
    type: 'feature-grid',
    label: 'Feature Grid',
    description: 'Grid of feature items',
    icon: '▦',
    category: 'layout',
    defaultStyles: {
      display: { base: 'grid' },
      gridTemplateColumns: { base: 'repeat(3, 1fr)' },
      gap: { base: '24px' },
      width: { base: '100%' },
      padding: { base: '24px' },
    },
    defaultProps: {},
  },

  // ===== TYPOGRAPHY =====
  {
    type: 'heading',
    label: 'Heading',
    description: 'Section heading (h1-h6)',
    icon: 'H',
    category: 'typography',
    defaultStyles: {
      display: { base: 'block' },
      fontSize: { base: '32px' },
      fontWeight: { base: '700' },
      color: { base: '#111827' },
      lineHeight: { base: '1.2' },
    },
    defaultProps: { text: 'Heading', level: 2 },
  },
  {
    type: 'blockquote',
    label: 'Blockquote',
    description: 'Quoted text block',
    icon: '❝',
    category: 'typography',
    defaultStyles: {
      display: { base: 'block' },
      padding: { base: '12px 16px' },
      borderLeft: { base: '4px solid #8b5cf6' },
      fontSize: { base: '16px' },
      fontStyle: { base: 'italic' },
      color: { base: '#6b7280' },
      backgroundColor: { base: '#f9fafb' },
      borderRadius: { base: '4px' },
    },
    defaultProps: { text: 'Blockquote text' },
  },
  {
    type: 'list',
    label: 'List',
    description: 'Ordered or unordered list',
    icon: '≡',
    category: 'typography',
    defaultStyles: {
      display: { base: 'block' },
      padding: { base: '0 0 0 24px' },
      fontSize: { base: '16px' },
      color: { base: '#374151' },
      lineHeight: { base: '1.75' },
    },
    defaultProps: { items: 'Item 1\nItem 2\nItem 3', ordered: false },
  },
  {
    type: 'code-block',
    label: 'Code Block',
    description: 'Preformatted code display',
    icon: '</>',
    category: 'typography',
    defaultStyles: {
      display: { base: 'block' },
      padding: { base: '16px' },
      backgroundColor: { base: '#1e293b' },
      color: { base: '#e2e8f0' },
      fontSize: { base: '14px' },
      fontFamily: { base: 'monospace' },
      borderRadius: { base: '8px' },
      overflow: { base: 'auto' },
      lineHeight: { base: '1.5' },
    },
    defaultProps: { text: 'const x = 42;', language: 'javascript' },
  },

  // ===== MEDIA =====
  {
    type: 'image',
    label: 'Image',
    description: 'Display an image from URL',
    icon: '◎',
    category: 'media',
    defaultStyles: {
      display: { base: 'block' },
      width: { base: '100%' },
      maxWidth: { base: '300px' },
      borderRadius: { base: '8px' },
    },
    defaultProps: { src: '', alt: 'Image' },
  },
  {
    type: 'video',
    label: 'Video Embed',
    description: 'Embedded video player',
    icon: '▶',
    category: 'media',
    defaultStyles: {
      display: { base: 'block' },
      width: { base: '100%' },
      aspectRatio: { base: '16 / 9' },
      backgroundColor: { base: '#111827' },
      borderRadius: { base: '8px' },
    },
    defaultProps: { embedUrl: '' },
  },
  {
    type: 'icon',
    label: 'Icon',
    description: 'Single icon display',
    icon: '✦',
    category: 'media',
    defaultStyles: {
      display: { base: 'inline-flex' },
      width: { base: '24px' },
      height: { base: '24px' },
      alignItems: { base: 'center' },
      justifyContent: { base: 'center' },
      fontSize: { base: '24px' },
    },
    defaultProps: { iconName: 'star', text: '✦' },
  },
  {
    type: 'icon-grid',
    label: 'Icon Grid',
    description: 'Grid of icon items',
    icon: '▤',
    category: 'media',
    defaultStyles: {
      display: { base: 'grid' },
      gridTemplateColumns: { base: 'repeat(4, 1fr)' },
      gap: { base: '16px' },
      width: { base: '100%' },
      padding: { base: '16px' },
    },
    defaultProps: {},
  },
  {
    type: 'gallery',
    label: 'Image Gallery',
    description: 'Grid of images',
    icon: '▣',
    category: 'media',
    defaultStyles: {
      display: { base: 'grid' },
      gridTemplateColumns: { base: 'repeat(3, 1fr)' },
      gap: { base: '8px' },
      width: { base: '100%' },
    },
    defaultProps: {},
  },
];

export const getBlueprintByType = (type: ComponentType): ComponentBlueprint | undefined => {
  return componentBlueprints.find((bp) => bp.type === type);
};

export const getBlueprintsByCategory = (category: BlueprintCategory): ComponentBlueprint[] => {
  return componentBlueprints.filter((bp) => bp.category === category);
};

export const categories = [
  { id: 'basic', label: 'Basic', icon: '□' },
  { id: 'layout', label: 'Layout', icon: '▦' },
  { id: 'form', label: 'Form', icon: '▢' },
  { id: 'navigation', label: 'Navigation', icon: '☰' },
  { id: 'data', label: 'Data', icon: '⊞' },
  { id: 'feedback', label: 'Feedback', icon: '⚡' },
  { id: 'typography', label: 'Typography', icon: 'T' },
  { id: 'media', label: 'Media', icon: '◎' },
  { id: 'templates', label: 'Templates', icon: '♛' },
] as const;
